version: '3'
services:
    server:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "${APP_DOCKER_HOST_PORT}:80"
        links:
            - php
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/logo_shop'
        links:
            - database

    database:
        image: postgres:13
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
